// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/splash-variants/Glitch.tsx": () => import("../components/mockups/splash-variants/Glitch.tsx"),
  "./components/mockups/splash-variants/Particles.tsx": () => import("../components/mockups/splash-variants/Particles.tsx"),
  "./components/mockups/splash-variants/Typewriter.tsx": () => import("../components/mockups/splash-variants/Typewriter.tsx")
};
